// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBodOAxudoQeB5oAWI8qaFjsg7cCPo92B0',
    appId: '1:72267940901:web:64f76c72e2c231c785abcc',
    messagingSenderId: '72267940901',
    projectId: 'e-commerce-app-f98c4',
    authDomain: 'e-commerce-app-f98c4.firebaseapp.com',
    storageBucket: 'e-commerce-app-f98c4.appspot.com',
    measurementId: 'G-B6D2WSEFQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmi7PIdFKAA0vIFz5x4aFXDqNhj7qphgY',
    appId: '1:72267940901:android:883397be7cdbe1a885abcc',
    messagingSenderId: '72267940901',
    projectId: 'e-commerce-app-f98c4',
    storageBucket: 'e-commerce-app-f98c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkiLmjRCzS3Ri1PeHwVFQJJXLZ4hcJJUY',
    appId: '1:72267940901:ios:ebf77bb65006d37185abcc',
    messagingSenderId: '72267940901',
    projectId: 'e-commerce-app-f98c4',
    storageBucket: 'e-commerce-app-f98c4.appspot.com',
    iosBundleId: 'com.example.cpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkiLmjRCzS3Ri1PeHwVFQJJXLZ4hcJJUY',
    appId: '1:72267940901:ios:ebf77bb65006d37185abcc',
    messagingSenderId: '72267940901',
    projectId: 'e-commerce-app-f98c4',
    storageBucket: 'e-commerce-app-f98c4.appspot.com',
    iosBundleId: 'com.example.cpl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBodOAxudoQeB5oAWI8qaFjsg7cCPo92B0',
    appId: '1:72267940901:web:4c1655e4682ed7e185abcc',
    messagingSenderId: '72267940901',
    projectId: 'e-commerce-app-f98c4',
    authDomain: 'e-commerce-app-f98c4.firebaseapp.com',
    storageBucket: 'e-commerce-app-f98c4.appspot.com',
    measurementId: 'G-99END2K9MG',
  );

}